global using global::System;
global using Translating.Web.Domain.Models;
global using Translating.Web.Domain.Repositories;
global using Grpc.Core;
global using Grpc.Core.Interceptors;
global using Microsoft.AspNetCore.Authentication.OpenIdConnect;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Mvc;
global using OpenIddict.Client.AspNetCore;
global using static OpenIddict.Client.WebIntegration.OpenIddictClientWebIntegrationConstants;
global using OpenIddict.Abstractions;
global using static OpenIddict.Abstractions.OpenIddictConstants;
global using System.Security.Claims;
